// <auto-generated />
using System;
using HojasPersonaje.Backend.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HojasPersonaje.Backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260609202409_ModificarEspecialidadHabilidadTabla")]
    partial class ModificarEspecialidadHabilidadTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.AtributoHoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Astucia")
                        .HasColumnType("integer");

                    b.Property<int>("Carisma")
                        .HasColumnType("integer");

                    b.Property<int>("Compostura")
                        .HasColumnType("integer");

                    b.Property<int>("Destreza")
                        .HasColumnType("integer");

                    b.Property<int>("Fuerza")
                        .HasColumnType("integer");

                    b.Property<int>("HojaPersonajeId")
                        .HasColumnType("integer");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("integer");

                    b.Property<int>("Manipulacion")
                        .HasColumnType("integer");

                    b.Property<int>("Resistencia")
                        .HasColumnType("integer");

                    b.Property<int>("Resolucion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HojaPersonajeId");

                    b.ToTable("AtributosHojas");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Background", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HojaPersonajeId")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HojaPersonajeId");

                    b.ToTable("Backgrounds");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Biografia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apariencia")
                        .HasColumnType("text");

                    b.Property<int>("EdadAparente")
                        .HasColumnType("integer");

                    b.Property<int>("EdadReal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaMuerte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Historia")
                        .HasColumnType("text");

                    b.Property<int>("HojaPersonajeId")
                        .HasColumnType("integer");

                    b.Property<string>("RastosDistintivos")
                        .HasColumnType("text");

                    b.Property<string>("Resumen")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HojaPersonajeId");

                    b.ToTable("Biografias");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.ConviccionPiedra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Convicciones")
                        .HasColumnType("text");

                    b.Property<int>("HojaPersonajeId")
                        .HasColumnType("integer");

                    b.Property<string>("PiedraToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HojaPersonajeId");

                    b.ToTable("ConviccionesPiedras");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Cronica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<int?>("CronicaId")
                        .HasColumnType("integer");

                    b.Property<int>("DungeonMasterId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreCronica")
                        .HasColumnType("text");

                    b.Property<string>("PaisCronica")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CronicaId");

                    b.HasIndex("DungeonMasterId");

                    b.ToTable("Cronicas");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.EspecialidadHabilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .HasColumnType("text");

                    b.Property<string>("HabilidadEspecialidad")
                        .HasColumnType("text");

                    b.Property<int>("habilidadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("habilidadId");

                    b.ToTable("EspecialidadesHabilidades");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.ExperienciaHoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienciaGastada")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienciaTotal")
                        .HasColumnType("integer");

                    b.Property<int>("HojaPersonajeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HojaPersonajeId");

                    b.ToTable("ExperienciasHojas");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Flaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HojaPersonajeId")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HojaPersonajeId");

                    b.ToTable("Flaws");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Habilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Academicismo")
                        .HasColumnType("integer");

                    b.Property<int>("Actuacion")
                        .HasColumnType("integer");

                    b.Property<int>("AnimalKen")
                        .HasColumnType("integer");

                    b.Property<int>("ArmasFuego")
                        .HasColumnType("integer");

                    b.Property<int>("Astucia")
                        .HasColumnType("integer");

                    b.Property<int>("Atletismo")
                        .HasColumnType("integer");

                    b.Property<int>("Ciencia")
                        .HasColumnType("integer");

                    b.Property<int>("Conduccion")
                        .HasColumnType("integer");

                    b.Property<int>("Consciencia")
                        .HasColumnType("integer");

                    b.Property<int>("Crafteo")
                        .HasColumnType("integer");

                    b.Property<int>("Etiqueta")
                        .HasColumnType("integer");

                    b.Property<int>("Finanzas")
                        .HasColumnType("integer");

                    b.Property<int>("HojaPersonajeId")
                        .HasColumnType("integer");

                    b.Property<int>("Insight")
                        .HasColumnType("integer");

                    b.Property<int>("Intimidacion")
                        .HasColumnType("integer");

                    b.Property<int>("Investigacion")
                        .HasColumnType("integer");

                    b.Property<int>("Latrocinio")
                        .HasColumnType("integer");

                    b.Property<int>("Liderazgo")
                        .HasColumnType("integer");

                    b.Property<int>("Medicina")
                        .HasColumnType("integer");

                    b.Property<int>("Melee")
                        .HasColumnType("integer");

                    b.Property<int>("Ocultismo")
                        .HasColumnType("integer");

                    b.Property<int>("Pelea")
                        .HasColumnType("integer");

                    b.Property<int>("Persuacion")
                        .HasColumnType("integer");

                    b.Property<int>("Politica")
                        .HasColumnType("integer");

                    b.Property<int>("Sigilo")
                        .HasColumnType("integer");

                    b.Property<int>("Subterfugio")
                        .HasColumnType("integer");

                    b.Property<int>("Supervivencia")
                        .HasColumnType("integer");

                    b.Property<int>("Tecnologia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HojaPersonajeId");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ambicion")
                        .HasColumnType("text");

                    b.Property<string>("Concepto")
                        .HasColumnType("text");

                    b.Property<int>("CronicaId")
                        .HasColumnType("integer");

                    b.Property<string>("Desire")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<int>("usuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CronicaId");

                    b.HasIndex("usuarioId");

                    b.ToTable("HojasPersonajes");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Merito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HojaPersonajeId")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HojaPersonajeId");

                    b.ToTable("Meritos");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HojaPersonajeId")
                        .HasColumnType("integer");

                    b.Property<string>("nota")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HojaPersonajeId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Posesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HojaPersonajeId")
                        .HasColumnType("integer");

                    b.Property<string>("posesion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HojaPersonajeId");

                    b.ToTable("Posesiones");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("HojaPersonajeId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HojaPersonajeId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Foto")
                        .HasColumnType("text");

                    b.Property<string>("Nombre_Usuario")
                        .HasColumnType("text");

                    b.Property<int>("tipoUsuario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.ClanBane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bane")
                        .HasColumnType("text");

                    b.Property<string>("Compulsion")
                        .HasColumnType("text");

                    b.Property<int>("vampiroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("vampiroId");

                    b.ToTable("DebilidadesClanes");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.DisciplinaJugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("disciplinaId")
                        .HasColumnType("integer");

                    b.Property<int>("hojasDePersonajeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("disciplinaId");

                    b.HasIndex("hojasDePersonajeId");

                    b.ToTable("DisciplinasJugadores");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.DisciplinaVampiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("disciplinaId")
                        .HasColumnType("integer");

                    b.Property<int>("vampiroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("disciplinaId");

                    b.HasIndex("vampiroId");

                    b.ToTable("DisciplinasVampiros");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.HabilidadDisciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enardecimiento")
                        .HasColumnType("boolean");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Tirada")
                        .HasColumnType("text");

                    b.Property<int>("disciplinaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("disciplinaId");

                    b.ToTable("HabilidadesDisciplinas");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.HabilidadesJugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("habilidadDisciplinaId")
                        .HasColumnType("integer");

                    b.Property<int>("hojasDePersonajeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("habilidadDisciplinaId");

                    b.HasIndex("hojasDePersonajeId");

                    b.ToTable("HabilidadesJugadores");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.HojaVampiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HojaPersonajeId")
                        .HasColumnType("integer");

                    b.Property<string>("Sire")
                        .HasColumnType("text");

                    b.Property<int>("TipoDepredadorId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HojaPersonajeId");

                    b.HasIndex("TipoDepredadorId");

                    b.ToTable("HojasVampiros");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.TipoDepredador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposDepredador");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.Vampiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vampiros");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.AtributoHoja", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "HojaPersonaje")
                        .WithMany("Atributos")
                        .HasForeignKey("HojaPersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaPersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Background", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "HojaPersonaje")
                        .WithMany("Backgrounds")
                        .HasForeignKey("HojaPersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaPersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Biografia", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "HojaPersonaje")
                        .WithMany("Biografias")
                        .HasForeignKey("HojaPersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaPersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.ConviccionPiedra", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "HojaPersonaje")
                        .WithMany("Convicciones")
                        .HasForeignKey("HojaPersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaPersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Cronica", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.Cronica", null)
                        .WithMany("Cronicas")
                        .HasForeignKey("CronicaId");

                    b.HasOne("HojasPersonaje.Backend.Entidades.Usuarios.Usuario", "DungeonMaster")
                        .WithMany("cronicas")
                        .HasForeignKey("DungeonMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DungeonMaster");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.EspecialidadHabilidad", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.Habilidad", "habilidad")
                        .WithMany("Especialidades")
                        .HasForeignKey("habilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("habilidad");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.ExperienciaHoja", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "HojaPersonaje")
                        .WithMany("Experiencias")
                        .HasForeignKey("HojaPersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaPersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Flaw", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "HojaPersonaje")
                        .WithMany("Flaws")
                        .HasForeignKey("HojaPersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaPersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Habilidad", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "HojaPersonaje")
                        .WithMany("Habilidades")
                        .HasForeignKey("HojaPersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaPersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.Cronica", "Cronica")
                        .WithMany()
                        .HasForeignKey("CronicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Backend.Entidades.Usuarios.Usuario", "usuario")
                        .WithMany("hojasPersonajes")
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cronica");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Merito", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "HojaPersonaje")
                        .WithMany("Meritos")
                        .HasForeignKey("HojaPersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaPersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Nota", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "HojaPersonaje")
                        .WithMany("Notas")
                        .HasForeignKey("HojaPersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaPersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Posesion", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "HojaPersonaje")
                        .WithMany("Posesiones")
                        .HasForeignKey("HojaPersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaPersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Weapon", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "HojaPersonaje")
                        .WithMany("Weapons")
                        .HasForeignKey("HojaPersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaPersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.ClanBane", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Vampiros.Vampiro", "vampiro")
                        .WithMany("DebilidadesClanes")
                        .HasForeignKey("vampiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vampiro");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.DisciplinaJugador", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Vampiros.Disciplina", "disciplina")
                        .WithMany("disciplinaJugadores")
                        .HasForeignKey("disciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "hojasDePersonaje")
                        .WithMany("disciplinaJugadores")
                        .HasForeignKey("hojasDePersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("disciplina");

                    b.Navigation("hojasDePersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.DisciplinaVampiro", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Vampiros.Disciplina", "disciplina")
                        .WithMany("disciplinaVampiros")
                        .HasForeignKey("disciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Backend.Entidades.Vampiros.Vampiro", "vampiro")
                        .WithMany("disciplinaVampiros")
                        .HasForeignKey("vampiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("disciplina");

                    b.Navigation("vampiro");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.HabilidadDisciplina", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Vampiros.Disciplina", "disciplina")
                        .WithMany("habilidadDisciplinas")
                        .HasForeignKey("disciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("disciplina");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.HabilidadesJugador", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Vampiros.HabilidadDisciplina", "habilidadDisciplina")
                        .WithMany("habilidadesJugadores")
                        .HasForeignKey("habilidadDisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "hojasDePersonaje")
                        .WithMany("habilidadesJugadores")
                        .HasForeignKey("hojasDePersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("habilidadDisciplina");

                    b.Navigation("hojasDePersonaje");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.HojaVampiro", b =>
                {
                    b.HasOne("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", "HojaPersonaje")
                        .WithMany("HojasVampiros")
                        .HasForeignKey("HojaPersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HojasPersonaje.Backend.Entidades.Vampiros.TipoDepredador", "TipoDepredador")
                        .WithMany("HojasVampiro")
                        .HasForeignKey("TipoDepredadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaPersonaje");

                    b.Navigation("TipoDepredador");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Cronica", b =>
                {
                    b.Navigation("Cronicas");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.Habilidad", b =>
                {
                    b.Navigation("Especialidades");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Hojas.HojasDePersonaje", b =>
                {
                    b.Navigation("Atributos");

                    b.Navigation("Backgrounds");

                    b.Navigation("Biografias");

                    b.Navigation("Convicciones");

                    b.Navigation("Experiencias");

                    b.Navigation("Flaws");

                    b.Navigation("Habilidades");

                    b.Navigation("HojasVampiros");

                    b.Navigation("Meritos");

                    b.Navigation("Notas");

                    b.Navigation("Posesiones");

                    b.Navigation("Weapons");

                    b.Navigation("disciplinaJugadores");

                    b.Navigation("habilidadesJugadores");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Usuarios.Usuario", b =>
                {
                    b.Navigation("cronicas");

                    b.Navigation("hojasPersonajes");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.Disciplina", b =>
                {
                    b.Navigation("disciplinaJugadores");

                    b.Navigation("disciplinaVampiros");

                    b.Navigation("habilidadDisciplinas");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.HabilidadDisciplina", b =>
                {
                    b.Navigation("habilidadesJugadores");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.TipoDepredador", b =>
                {
                    b.Navigation("HojasVampiro");
                });

            modelBuilder.Entity("HojasPersonaje.Backend.Entidades.Vampiros.Vampiro", b =>
                {
                    b.Navigation("DebilidadesClanes");

                    b.Navigation("disciplinaVampiros");
                });
#pragma warning restore 612, 618
        }
    }
}
